version: '3'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  flask_app:
    build:
      context: ..
      dockerfile: DS_testing/flask_app/Dockerfile
    container_name: flask_app
    ports:
      - "8080:8080"
    depends_on:
      - redis

  memory_monitor:
    build:
      context: ..
      dockerfile: DS_testing/memory_monitor/Dockerfile
    container_name: memory_monitor
    depends_on:
      - flask_app
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on:
      - memory_monitor
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus_config.yaml:/etc/prometheus/prometheus_config.yaml
    command:
      - --config.file=/etc/prometheus/prometheus_config.yaml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana

volumes:
  prometheus:
  grafana:
